apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: hustlr
build:
  artifacts:
  - image: frontend-image
    context: frontend
    docker:
      dockerfile: Dockerfile
  - image: backend-image
    context: backend
    docker:
      dockerfile: Dockerfile
  - image: ai-image
    context: ai-orchestrator
    docker:
      dockerfile: Dockerfile
manifests:
  rawYaml:
  - k8s/*.yaml
deploy:
  cloudrun:
    projectid: YOUR_PROJECT_ID
    region: us-central1
